[package]
name = "advent_of_code_2022"
version = "0.1.0"
author = ["noahares"]
edition = "2021"

[lib]
name = "libaoc"
path = "src/lib.rs"

[[bin]]
name = "day01"
path = "src/bin/day01.rs"

[[bin]]
name = "day02"
path = "src/bin/day02.rs"

[dependencies]
anyhow = "1.0.51"
itertools = "0.10.5"
